version: '3.8'

networks:
  yves-gendron-prod:

services:
  app-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app-yves-gendron
    restart: unless-stopped
    networks:
      - yves-gendron-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_INTERNAL_PORT}

      NST_API_URL: ${NST_API_URL}
      NST_BROWSER_API_KEY: ${NST_TOKEN}
    depends_on:
      - postgres_yves_gendron
      - nstbrowserless_gendron
    ports:
      - "${API_PORT}:8080"

  postgres_yves_gendron:
    image: postgres:16
    container_name: postgres-db-yves-gendron
    restart: unless-stopped
    networks:
      - yves-gendron-prod
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_yves_gendron_data:/var/lib/postgresql/data

  nstbrowserless_gendron:
    image: nstbrowser/browserless:140-202511181200.v2
    container_name: nstbrowserless-yves-gendron
    restart: unless-stopped
    networks:
      - yves-gendron-prod
    environment:
      TOKEN: ${NST_TOKEN}
      VNC_PORT: ${VNC_PORT}
      VNC_PASSWORD: ${VNC_PASSWORD}
    ports:
      - "${NST_PORT}:8848"
      - "${VNC_PORT}:6900"

volumes:
  pg_yves_gendron_data:
